name: track_weather
description: A new Flutter project.
publish_to: "none"
version: 0.3.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.2
  dio: ^5.3.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  http_mock_adapter: ^0.4.4

flutter:
  uses-material-design: true
